service: Gov-TLS-Audit

plugins:
  - serverless-apigw-binary # to allow binary data back from api Gateway
  - serverless-apigwy-binary # convert base64 data to binary

custom:
  apigwBinary:
    types:
      - 'application/zip'

package:
  exclude:
    - test/*
    - test*
    - venv/**

provider:
  name: aws
  runtime: python3.6
  region: us-west-2
  stage: Dev  
  memorySize: 128 # explicitly set to 128
  timeout: 10 # default is 6
  iamRoleStatements: # permissions for all of your functions can be set here
    - Effect: Allow
      Action: # Gives permission to DynamoDB tables in a specific region
        - dynamodb:Query
        - dynamodb:PutItem
        - dynamodb:BatchWriteItem
      Resource: "arn:aws:dynamodb:us-west-2:820756113164:table/siteAuditGovMy"
    - Effect: Allow
      Action:
        s3:ListBucket
      Resource: "arn:aws:s3:::files.siteaudit.sayakenahack.com"
    - Effect: Allow
      Action:
        s3:GetObject
      Resource: "arn:aws:s3:::files.siteaudit.sayakenahack.com/*"

versionFunctions: false # don't keep old versions (there's GIT for that)

functions:
  get_by_fqdn: # function Name
    handler: handler.get_by_fqdn # def within handler.py that will handle this
    name: ${opt:stage, self:provider.stage}-get_by_FQDN
    description: Get Full TLS Record for fqdn
    events:
      - http:
          path: siteDetails # path of this function
          method: get
          cors: true
  list_scans:
    handler: list_scans.list_scans
    name: ${opt:stage, self:provider.stage}-list_scans
    description: List scan files in S3 Bucket
    events:
      - http:
          path: listScans
          method: get
          cors: true
  download_zip:
    handler: download_scan.download_zip
    name: ${opt:stage, self:provider.stage}-download_scan
    description: Download scan files from S3
    timeout: 300 # maximum timeout for the downloads
    memorySize: 384 # more RAM = more CPU on lambda, need more CPU!
    reservedConcurrency: 3 # maximum number of concurrent downloads   
    events:
      - http:
          path: downloadScan
          method: get
          contentHandling: CONVERT_TO_BINARY
          # cors: true  # disabling cors on this end point

###
### Comment all below if you do not wish to create bucket & DynamoDB ###
###

# resources:  
  # Resources:
    # uploadbucket:
    #  DeletionPolicy: Retain
    #  Type: AWS::S3::Bucket
    #  Properties:
    #    BucketName: files.siteaudit.sayakenahack.com # Hard Code, change this later
    # SiteAuditTable:
      # Type: 'AWS::DynamoDB::Table'
      # DeletionPolicy: Retain  
      # Properties:
        # TableName: siteAuditGovMy # Hard Code, change this later
        # AttributeDefinitions:
          # - AttributeName: FQDN # FQDN is an acronym, hence CAPS :)
          #   AttributeType: S
          # - AttributeName: scanDate 
          #   AttributeType: S
        # KeySchema:
          # - AttributeName: FQDN
          #   KeyType: HASH
          # - AttributeName: scanDate
          #   KeyType: RANGE
        # ProvisionedThroughput:
          # ReadCapacityUnits: 2
          # WriteCapacityUnits: 1

