service: jangan-kena-hack

package:
  exclude:
    - test/*
    - venv/**
    - README.md
    - requirements.txt
    - .gitignore

provider:
  name: aws
  runtime: python3.6
  region: us-west-2
  stage: Dev  
  memorySize: 128 # explicitly set to 128
  timeout: 6 # default is 6
  iamRoleStatements: # permissions for all of your functions can be set here
    - Effect: Allow
      Action: # Gives permission to DynamoDB tables in a specific region
        - dynamodb:Query
        - dynamodb:PutItem
        - dynamodb:BatchWriteItem
      Resource: "arn:aws:dynamodb:us-west-2:*:*"
    - Effect: Allow
      Action:
        - s3:*  # Needed for DEBUG Later, should be specific..
      Resource: "*" # Needed for DEBUG Later, should be specific ARN

versionFunctions: false # don't keep old versions (there's GIT for that)

functions:
  get_by_fqdn: # function Name
    handler: handler.get_by_fqdn # def within handler.py that will handle this
    name: ${self:provider.stage}-get_by_FQDN
    description: Get Full TLS Record for fqdn
    events:
      - http:
          path: siteDetails # path of this function
          method: get
  insert_into_dynamo:
    handler: insert.insert_into_dynamo
    name: ${self:provider.stage}-insert_into_dynamo
    description: Insert into Dynamo from jsonl file in S3 Bucket. No events. Manual invocation.
    timeout: 300 #maximum allowed in lambda

###
### Comment all below if you do not wish to create bucket & DynamoDB ###
###

# resources:  
  # Resources:
    # uploadbucket:
    #  DeletionPolicy: Retain
    #  Type: AWS::S3::Bucket
    #  Properties:
    #    BucketName: siteAuditGovMy # Hard Code, change this later
    # SiteAuditTable:
      # Type: 'AWS::DynamoDB::Table'
      # DeletionPolicy: Retain  
      # Properties:
        # TableName: siteAuditGovMy # Hard Code, change this later
        # AttributeDefinitions:
          # - AttributeName: FQDN # FQDN is an acronym, hence CAPS :)
          #   AttributeType: S
          # - AttributeName: scanDate # FQDN is an acronym, hence CAPS :)
          #   AttributeType: S
        # KeySchema:
          # - AttributeName: FQDN
          #   KeyType: HASH
          # - AttributeName: scanDate
          #   KeyType: RANGE
        # ProvisionedThroughput:
          # ReadCapacityUnits: 2
          # WriteCapacityUnits: 1

